general.import = ["/home/simon/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "Inconsolata"

[font.bold_italic]
family = "Inconsolata"

[font.italic]
family = "Inconsolata"

[font.normal]
family = "Inconsolata"

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2

[window.position]
x = 0
y = 0
